spring:
  h2:
    console:
      enabled: true
  datasource:
    url: "jdbc:h2:mem:orders_db;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
    username: "sa"
    password:
    driver-class-name: org.h2.Driver
    initialization-mode: embedded
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000     # 30 seconds
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect